import os
import subprocess
import sys
from typing import Optional
from rich.console import Console

console = Console()

def wizard_mode(output_dir: Optional[str] = None):
    """Run tinytuya wizard."""
    console.print("[bold blue]Starting TinyTuya Wizard...[/bold blue]")

    workdir = None
    if output_dir:
        workdir = os.path.abspath(output_dir)
        os.makedirs(workdir, exist_ok=True)
        console.print(f"[blue]Using {workdir} for TinyTuya wizard files.[/blue]")

    try:
        # We shell out to python -m tinytuya wizard as it's an interactive CLI
        cmd = [sys.executable, "-m", "tinytuya", "wizard"]
        subprocess.run(cmd, check=True, cwd=workdir)

        if output_dir:
            output_files = [
                "devices.json",
                "snapshot.json",
                "tuya-raw.json",
                "tinytuya.json",
                "groups.json",
            ]
            if not any(os.path.exists(os.path.join(workdir, filename)) for filename in output_files):
                console.print("\n[yellow]Warning: No output files were generated by TinyTuya.[/yellow]")
                console.print("[yellow]This usually happens if there was an error during the wizard (e.g. API subscription expired).[/yellow]")

        console.print("\n[bold green]Wizard process finished![/bold green]")

        console.print("\n[bold]Next steps:[/bold]")
        console.print("1. Open the generated [cyan]devices.json[/cyan] to find your device IDs, IPs and Local Keys.")
        console.print("2. Update your [cyan]config.yaml[/cyan] with these details.")
        console.print("3. Restart the tuya2mqtt bridge.")

    except subprocess.CalledProcessError as e:
        console.print(f"[red]Error running TinyTuya wizard: {e}[/red]")
    except Exception as e:
        console.print(f"[red]An unexpected error occurred: {e}[/red]")
