import os
import shutil
import subprocess
import sys
import logging
from typing import Optional
from rich.console import Console

logger = logging.getLogger(__name__)
console = Console()

def wizard_mode(output_dir: Optional[str] = None):
    """Run tinytuya wizard."""
    console.print("[bold blue]Starting TinyTuya Wizard...[/bold blue]")
    
    if output_dir:
        os.makedirs(output_dir, exist_ok=True)
        # TinyTuya wizard usually creates devices.json and snapshot.json in current dir
        # We'll run it and then move files if needed
        # Actually it's better to just instructions users to mount their config dir
        pass

    try:
        # We shell out to python -m tinytuya wizard as it's an interactive CLI
        cmd = [sys.executable, "-m", "tinytuya", "wizard"]
        subprocess.run(cmd, check=True)
        
        if output_dir:
            # Check for files and move them
            moved_any = False
            for filename in ["devices.json", "snapshot.json", "tuya-raw.json", "tinytuya.json", "groups.json"]:
                if os.path.exists(filename):
                    dest = os.path.join(output_dir, filename)
                    shutil.move(filename, dest)
                    console.print(f"[green]Moved {filename} to {dest}[/green]")
                    moved_any = True
                else:
                    logger.debug(f"File {filename} not found, skipping.")

            if not moved_any:
                console.print("\n[yellow]Warning: No output files were generated by TinyTuya.[/yellow]")
                console.print("[yellow]This usually happens if there was an error during the wizard (e.g. API subscription expired).[/yellow]")
        
        console.print("\n[bold green]Wizard process finished![/bold green]")

        console.print("\n[bold]Next steps:[/bold]")
        console.print("1. Open the generated [cyan]devices.json[/cyan] to find your device IDs, IPs and Local Keys.")
        console.print("2. Update your [cyan]config.yaml[/cyan] with these details.")
        console.print("3. Restart the tuya2mqtt bridge.")

    except subprocess.CalledProcessError as e:
        console.print(f"[red]Error running TinyTuya wizard: {e}[/red]")
    except Exception as e:
        console.print(f"[red]An unexpected error occurred: {e}[/red]")